---
ngrok:
  image: 'eschizoid/docker-ngrok-armhf'
  restart: always
  command: ngrok http dockerAlexaHue:4567 -log stdout -log-level debug
  links:
    - dockerAlexaHue
dockerAlexaHue:
  image: 'eschizoid/docker-alexa-hue-armhf'
  restart: always
  environment:
    TZ: ${TIMEZONE}
